src/Entity/Plante.php
<?php

namespace App\Entity;

use App\Repository\PlanteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlanteRepository::class)]
class Plante
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;



    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 200)]
    private ?string $image = null;

    /**
     * @var Collection<int, Molecule>
     */
    #[ORM\OneToMany(targetEntity: Molecule::class, mappedBy: 'idPlante')]
    private Collection $molecules;

    /**
     * @var Collection<int, Cadenas>
     */
    #[ORM\OneToMany(targetEntity: Cadenas::class, mappedBy: 'idPlante')]
    private Collection $cadenas;

    /**
     * @var Collection<int, Partie>
     */
    #[ORM\OneToMany(targetEntity: Partie::class, mappedBy: 'idPlante')]
    private Collection $parties;

    public function __construct()
    {
        $this->molecules = new ArrayCollection();
        $this->cadenas = new ArrayCollection();
        $this->parties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, Molecule>
     */
    public function getMolecules(): Collection
    {
        return $this->molecules;
    }

    public function addMolecule(Molecule $molecule): static
    {
        if (!$this->molecules->contains($molecule)) {
            $this->molecules->add($molecule);
            $molecule->setIdPlante($this);
        }

        return $this;
    }

    public function removeMolecule(Molecule $molecule): static
    {
        if ($this->molecules->removeElement($molecule)) {
            // set the owning side to null (unless already changed)
            if ($molecule->getIdPlante() === $this) {
                $molecule->setIdPlante(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Cadenas>
     */
    public function getCadenas(): Collection
    {
        return $this->cadenas;
    }

    public function addCadena(Cadenas $cadena): static
    {
        if (!$this->cadenas->contains($cadena)) {
            $this->cadenas->add($cadena);
            $cadena->setIdPlante($this);
        }

        return $this;
    }

    public function removeCadena(Cadenas $cadena): static
    {
        if ($this->cadenas->removeElement($cadena)) {
            // set the owning side to null (unless already changed)
            if ($cadena->getIdPlante() === $this) {
                $cadena->setIdPlante(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Partie>
     */
    public function getParties(): Collection
    {
        return $this->parties;
    }

    public function addParty(Partie $party): static
    {
        if (!$this->parties->contains($party)) {
            $this->parties->add($party);
            $party->setIdPlante($this);
        }

        return $this;
    }

    public function removeParty(Partie $party): static
    {
        if ($this->parties->removeElement($party)) {
            // set the owning side to null (unless already changed)
            if ($party->getIdPlante() === $this) {
                $party->setIdPlante(null);
            }
        }

        return $this;
    }
    public function getFormuleChimique(): ?string
    {
        return $this->formule_chimique;
    }

    public function setFormuleChimique(?string $formule_chimique): self
    {
        $this->formule_chimique = $formule_chimique;
        return $this;
    }
}

src/Controller/JeuController.php
<?php

namespace App\Controller;

use App\Entity\Plante;
use App\Entity\Partie;
use App\Repository\PlanteRepository;
use App\Repository\MoleculeRepository;
use App\Repository\CadenasRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

class JeuController extends AbstractController
{
    #[Route('/', name: 'accueil')]
    public function index(): Response
    {
        return $this->render('jeu/accueil.html.twig');
    }


    #[Route('/jeu', name: 'commencer_jeu')]
    public function startGame(
        PlanteRepository $planteRepository,
        MoleculeRepository $moleculeRepository,
        EntityManagerInterface $entityManager,
        SessionInterface $session,
        Request $request
    ): Response {

        if ($request->query->get('from') === 'accueil' || !$session->has('global_start_time')) {
            $session->set('global_start_time', time());
            $session->set('parties_jouees', 0);
            $session->set('formules_trouvees', []);
            $session->set('plantes_jouees', []);
            $session->set('score', 0);
        }


        $partiesJouees = count($session->get('plantes_jouees', []));
        $session->set('parties_jouees', $partiesJouees);


        if ($partiesJouees >= 4) {
            return $this->redirectToRoute('resultat', [
                'success' => true,
                'timeout' => false,
                'parties_jouees' => $partiesJouees,
                'score' => $session->get('score', 0)
            ]);
        }


        $globalStartTime = $session->get('global_start_time');
        $timeElapsed = time() - $globalStartTime;
        $timeRemaining = 300 - $timeElapsed;

        if ($timeRemaining <= 0) {
            return $this->redirectToRoute('resultat', [
                'success' => false,
                'timeout' => true,
                'parties_jouees' => $partiesJouees
            ]);
        }


        $plantesJouees = $session->get('plantes_jouees', []);
        $plante = $planteRepository->findRandomPlante($plantesJouees);

        if (!$plante) {
            return $this->redirectToRoute('resultat', [
                'success' => true,
                'timeout' => false,
                'parties_jouees' => $partiesJouees,
                'score' => $session->get('score', 0)
            ]);
        }

        $molecules = $moleculeRepository->findBy(['plante' => $plante->getId()]);


        $partie = new Partie();
        $partie->setPlante($plante);
        $partie->setEtat('en_cours');
        $partie->setScore(0);

        $entityManager->persist($partie);
        $entityManager->flush();


        $plantesJouees[] = $plante->getId();
        $session->set('plantes_jouees', $plantesJouees);
        $session->set('plante_id', $plante->getId());
        $session->set('partie_id', $partie->getId());
        $session->set('molecules', $molecules);


        $partiesJouees = count($plantesJouees);
        $session->set('parties_jouees', $partiesJouees);

        return $this->render('jeu/decryptage.html.twig', [
            'plante' => $plante,
            'molecules' => $molecules,
            'timeRemaining' => $timeRemaining,
            'parties_jouees' => $partiesJouees
        ]);
    }
    #[Route('/valider', name: 'validate_answer')]
    public function validateAnswer(
        Request $request,
        SessionInterface $session,
        CadenasRepository $cadenasRepository,
        EntityManagerInterface $entityManager
    ): JsonResponse {
        $data = json_decode($request->getContent(), true);
        $planteId = $session->get('plante_id');
        $partieId = $session->get('partie_id');

        $globalStartTime = $session->get('global_start_time');
        $currentTime = time();
        $timeElapsed = $currentTime - $globalStartTime;
        $timeRemaining = 300 - $timeElapsed;


        $score = $session->get('score', 0);

        $cadenas = $cadenasRepository->findOneBy(['plante' => $planteId]);
        $motSecret = $cadenas->getMotSecret();


        $partie = $entityManager->getRepository(Partie::class)->find($partieId);
        $codeSaisi = trim(strtolower($data['code']));
        $motSecret = trim(strtolower($motSecret));

        $isCodeCorrect = ($codeSaisi === $motSecret);

        if ($timeRemaining <= 0) {
            if ($partie) {
                $partie->setEtat($isCodeCorrect ? 'terminee' : 'echec');
                $partie->setScore($score);
                $entityManager->persist($partie);
                $entityManager->flush();
            }

            return new JsonResponse([
                'status' => 'timeout',
                'redirectUrl' => $this->generateUrl('resultat', [
                    'success' => $isCodeCorrect,
                    'timeout' => true,
                    'parties_jouees' => $session->get('parties_jouees', 0),
                    'score' => $score
                ])
            ]);
        }


        if ($isCodeCorrect) {
            $score += 1;
            $session->set('score', $score);

            $plantesJouees = $session->get('plantes_jouees', []);
            $partiesJouees = count($plantesJouees);
            $session->set('parties_jouees', $partiesJouees);

            if ($partie) {
                $partie->setScore($score);
                $partie->setEtat('terminee');
                $entityManager->persist($partie);
                $entityManager->flush();
            }

            return new JsonResponse([
                'status' => 'success',
                'redirectUrl' => $this->generateUrl('resultat', [
                    'success' => true,
                    'timeout' => false,
                    'parties_jouees' => $partiesJouees,
                    'score' => $score
                ])
            ]);
        }


        if ($partie) {
            $partie->setEtat('echec');
            $partie->setScore($score);
            $entityManager->persist($partie);
            $entityManager->flush();
        }

        return new JsonResponse([
            'status' => 'failure',
            'redirectUrl' => $this->generateUrl('resultat', [
                'success' => false,
                'timeout' => false,
                'parties_jouees' => $session->get('parties_jouees'),
                'score' => $score
            ])
        ]);
    }
    #[Route('/resultat', name: 'resultat')]
    public function showResult(
        Request $request,
        SessionInterface $session,
        EntityManagerInterface $entityManager
    ): Response {
        $isSuccess = $request->query->get('success', false);
        $isTimeout = $request->query->get('timeout', false);
        $score = $session->get('score', 0);
        $partieId = $session->get('partie_id');

        $plantesJouees = $session->get('plantes_jouees', []);
        $partiesJouees = count($plantesJouees);

        $session->set('parties_jouees', $partiesJouees);
        $tentativeRejouerApres4 = $partiesJouees >= 4 && $request->query->get('rejouer', false);
        $partie = $entityManager->getRepository(Partie::class)->find($partieId);
        $plante = $partie ? $partie->getPlante() : null;

        return $this->render('jeu/resultat.html.twig', [
            'isSuccess' => $isSuccess,
            'isTimeout' => $isTimeout,
            'score' => $score,
            'plante' => $plante,
            'parties_jouees' => $partiesJouees,
            'tentativeRejouerApres4' => $tentativeRejouerApres4,
        ]);
    }

}

templates/jeu/accueil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Le Code Secret des Plantes{% endblock %}

{% block stylesheets %}
    <style>
        body {
            background-color: #f0f5f0;
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 20px;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .container {
            max-width: 800px;
            width: 90%;
            text-align: center;
            padding: 30px;
            background: white;
            border-radius: 20px;
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
        }

        h1 {
            color: #2c5282; /* Bleu foncé élégant */
            font-size: 2.2rem;
            margin-bottom: 30px;
            font-weight: 600;
        }

        .card {
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 15px;
            padding: 25px;
            margin-bottom: 30px;
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
        }

        .card-body h2 {
            color: #2c5282;
            font-size: 1.5rem;
            margin-bottom: 20px;
            font-weight: 600;
        }

        .card-body p {
            color: #4a5568;
            font-size: 1.1rem;
            line-height: 1.6;
            margin-bottom: 15px;
        }

        .btn-primary {
            background-color: #3182ce; /* Bleu vif */
            border: none;
            padding: 12px 30px;
            font-size: 1.1rem;
            border-radius: 10px;
            color: white;
            text-decoration: none;
            display: inline-block;
            transition: all 0.2s ease;
            font-weight: 500;
        }

        .btn-primary:hover {
            background-color: #2c5282;
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(49, 130, 206, 0.2);
        }


        p {
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 10px;
        }
        .example-box {
            border: 1px solid #e2e8f0;
            border-radius: 10px;
            padding: 20px;
            margin: 20px 0;
            background-color: #f8fafc;
            text-align: left;
        }
        .example-content p {
            margin: 15px 0;
        }

        .note {
            margin-top: 20px;
            line-height: 1.6;
        }

        /* Responsive design */
        @media (max-width: 480px) {
            .container {
                padding: 20px;
            }

            h1 {
                font-size: 1.8rem;
            }

            .card-body h2 {
                font-size: 1.3rem;
            }

            .card-body p {
                font-size: 1rem;
            }

            .btn-primary {
                padding: 10px 25px;
                font-size: 1rem;
            }
        }
        .example-box {
            border: 1px solid #e2e8f0;
            border-radius: 10px;
            padding: 15px;
            margin: 15px auto; /* centré */
            background-color: #f8fafc;
            text-align: left;
            cursor: pointer;
            max-width: 400px;
            transition: all 0.3s ease;
        }

        .example-box:hover {
            background-color: #f0f0f0;
        }

        .example-content {
            display: none;
            font-size: 0.9rem;
            margin-top: 10px;
        }

        .example-box.active .example-content {
            display: block;
        }

        .example-box h4 {
            margin: 0;
            font-size: 1rem;
            color: #4a5568;
            text-align: center;
            position: relative;
        }

        .example-box h4::after {
            content: '▼';
            position: absolute;
            right: 0;
            top: 50%;
            transform: translateY(-50%);
            transition: transform 0.3s ease;
        }

        .example-box.active h4::after {
            transform: translateY(-50%) rotate(180deg);
        }

        .rules {
            margin-top: 15px;
            padding-left: 20px;
        }

        .rules li {
            margin-bottom: 10px;
        }
        h1 {
            font-family: 'Poppins', sans-serif; /* Police Poppins */
            color: #2c5282; /* Bleu foncé élégant */
            font-size: 1.5rem; /* Taille réduite */
            font-weight: 700;
            text-align: center;
            letter-spacing: 1px;
            position: relative;
            display: inline-block;
            animation: fadeInUp 1s ease-out forwards;
        }

        h1::before {
            content: "";
            position: absolute;
            width: 100%;
            height: 4px;
            background-color: #3182ce; /* Bleu vif */
            bottom: -8px;
            left: 0;
            transform: scaleX(0);
            transform-origin: bottom right;
            animation: scaleIn 0.6s ease-out forwards;
        }
        @keyframes fadeInUp {
            0% {
                opacity: 0;
                transform: translateY(30px);
            }
            100% {
                opacity: 1;
                transform: translateY(0);
            }
        }


        @keyframes scaleIn {
            0% {
                transform: scaleX(0);
            }
            100% {
                transform: scaleX(1);
            }
        }

    </style>
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Le Jardin Des Secrets</h1>

        <div class="card">
            <div class="card-body">
                <h2>Comment jouer ?</h2>
                <p>🔍 Analysez 5 formules chimiques.</p>
                <p>🔢 Comptez les molécules dans chaque formule.</p>
                <p>🔤 Associez chaque nombre à une lettre (1=a, 2=b, etc.).</p>
                <p>🌱 Assemblez les lettres, afin de former le code secret pour afficher la plante !</p>
                <p> Si le code inséré est incorrect, une plante sauvage s'affichera ; sinon, le cadenas s'ouvrira et la plante correspondant aux molécules affichées sera révélée.</p>
                <div class="example-box">
                    <h4><i>Exemple <br>(Cliquez pour voir)</i></h4>
                    <div class="example-content">
                        <p>Formule chimique : <strong>H₂O</strong></p>
                        <p>Nombre de molécules : <strong>3</strong></p>
                        <p>Lettre correspondante : <strong>c</strong></p>
                    <p class="note">
                        Continuez ainsi avec les autres formules pour former le code complet. Voici quelques règles importantes:
                    </p>
                    <ul class="rules">
                        <li>Si le nombre dépasse <strong>26</strong> (le nombre de lettres de l'alphabet), recommencez au début. Par exemple : <strong>27 = a</strong>.</li>
                        <li>Si le nombre dépasse <strong>52</strong> (26 + 26), recommencez également au début. Par exemple : <strong>53 = a</strong>.</li>
                        <li>Le même principe s'applique pour les nombres encore plus grands.</li>
                    </ul>
                    </div>
                </div>
            </div>
        </div>

        <a href="{{ path('commencer_jeu', {'from': 'accueil'}) }}" class="btn btn-primary">Commencer</a>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            document.querySelector('.example-box').addEventListener('click', function() {
                this.classList.toggle('active');
            });
        });
    </script>
{% endblock %}

templates/jeu/decryptage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Décryptage des formules{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        body {
            background-color: #f0f5f0;
            font-family: 'Arial', sans-serif;
            padding: 20px;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .container {
            max-width: 800px;
            width: 90%;
            margin: 20px auto;
            padding: 30px;
            background: white;
            border-radius: 20px;
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
        }

        h1 {
            color: #2c5282;
            font-size: 2.2rem;
            margin-bottom: 30px;
            text-align: center;
            font-weight: 600;
        }


        .timer {
            background: #f8fafc;
            border: 2px solid #e2e8f0;
            border-radius: 12px;
            padding: 15px 25px;
            font-size: 1.8rem;
            color: #2c5282;
            display: inline-block;
            margin: 20px auto;
            font-weight: 600;
        }


        .card {
            background: #ffffff;
            border: 1px solid #e2e8f0;
            border-radius: 15px;
            padding: 25px;
            margin-bottom: 25px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);
        }

        .card-title {
            color: #2c5282;
            font-size: 1.4rem;
            margin-bottom: 20px;
            font-weight: 600;
        }

        .formula-box {
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            padding: 15px;
            border-radius: 10px;
            margin: 15px 0;
        }

        .formula-box h4 {
            color: #2d3748;
            margin: 0;
            font-size: 1.2rem;
        }

        .img-fluid {
            background-color: #ffffff;
            padding: 10px;
            border: 1px solid #e2e8f0;
            border-radius: 10px;
            max-height: 200px;
            margin: 15px auto;
            display: block;
            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.05);
        }

        #answer-zone {
            background: #f8fafc;
            padding: 25px;
            border-radius: 15px;
            margin-top: 30px;
            border: 1px solid #e2e8f0;
        }

        #final-code {
            background: #ffffff;
            border: 2px solid #3182ce;
            border-radius: 8px;
            padding: 10px;
            font-size: 1.2rem;
            text-align: center;
            color: #2d3748;
            max-width: 200px;
            margin: 15px auto;
            transition: border-color 0.2s ease;
        }

        #final-code:focus {
            outline: none;
            border-color: #2c5282;
            box-shadow: 0 0 0 3px rgba(49, 130, 206, 0.1);
        }

        label {
            color: #2d3748;
            font-weight: 600;
            font-size: 1.1rem;
        }

        .btn-primary {
            background-color: #3182ce;
            border: none;
            padding: 12px 30px;
            font-size: 1.1rem;
            border-radius: 10px;
            color: white;
            font-weight: 500;
            transition: all 0.2s ease;
        }

        .btn-primary:hover {
            background-color: #2c5282;
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(49, 130, 206, 0.2);
        }

        .timer.warning {
            color: #e53e3e;
            border-color: #e53e3e;
        }


        @media (max-width: 480px) {
            .container {
                padding: 15px;
            }

            .timer {
                font-size: 1.5rem;
                padding: 10px 20px;
            }

            .card {
                padding: 15px;
            }

            .card-title {
                font-size: 1.2rem;
            }

            #final-code {
                width: 80%;
            }
        }
    </style>
{% endblock %}


{% block body %}
    <div class="container">
        <h1 class="text-center my-4">Trouvez le code secret</h1>

        <div id="game-container">
            <div class="timer mb-4 text-center">
                Temps restant : <span id="global-timer">5:00</span>
            </div>
            <div id="formules-container">
                {% for molecule in molecules %}
                    <div class="formule" data-index="{{ loop.index0 }}" style="display: none;">
                        <div class="card h-100">
                            <div class="card-body text-center">
                                <h3 class="card-title">Formule {{ loop.index }}</h3>
                                <div class="formula-box mb-3">
                                    <h4>{{ molecule.formuleChimique }}</h4>
                                    <h3>{{ molecule.image|replace({'.png': ''}) }}</h3>
                                </div>
                                {% if molecule.image %}
                                    <img src="{{ asset('images/molecules/' ~ molecule.image) }}"
                                         alt="Molécule {{ molecule.formuleChimique }}"
                                         class="img-fluid mb-3"
                                         style="max-height: 200px; width: auto;">
                                {% endif %}

                                <i><p class="card-text">{{ molecule.information }}</p></i>

                            </div>
                        </div>
                    </div>
                {%  endfor %}
            </div>


            <div id="answer-zone" class="text-center mt-4">
                <div class="form-group">
                    <label for="final-code" class="mb-2">
                        <strong>Entrez le code secret :</strong>
                    </label>
                    <input type="text" id="final-code" name="code" class="form-control mx-auto" style="max-width: 200px;" required>
                </div>
                <button type="submit" class="btn btn-primary mt-3">Valider</button>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const globalTimerElement = document.getElementById('global-timer');
            const validateButton = document.querySelector('button[type="submit"]');
            const finalCodeInput = document.getElementById('final-code');
            const formules = document.querySelectorAll('.formule');

            let globalTimeRemaining = {{ timeRemaining }};
            let formulaTimeInterval = 1;
            let currentFormulaIndex = 0;

            function showNextFormula() {
                if (currentFormulaIndex < formules.length) {
                    formules[currentFormulaIndex].style.display = 'block';
                    currentFormulaIndex++;
                    if (currentFormulaIndex < formules.length) {
                        setTimeout(showNextFormula, formulaTimeInterval * 1000);
                    }
                }
            }


            showNextFormula();


            const style = document.createElement('style');
            style.textContent = `
                @keyframes pulse {
                    0% { transform: scale(1); }
                    50% { transform: scale(1.1); }
                    100% { transform: scale(1); }
                }
            `;
            document.head.appendChild(style);


            const globalTimer = setInterval(() => {
                if (globalTimeRemaining <= 0) {
                    clearInterval(globalTimer);
                    window.location.href = "{{ path('resultat', {
                        'success': false,
                        'timeout': true,
                        'parties_jouees': parties_jouees|default(0),
                        'score': 0
                    }) }}";
                    return;
                }


                if (globalTimeRemaining % 5 === 0) {
                    fetch('{{ path('validate_answer') }}', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                        },
                        body: JSON.stringify({ checkTime: true })
                    })
                        .then(response => response.json())
                        .then(data => {
                            if (data.status === 'timeout') {
                                window.location.href = data.redirectUrl;
                            }
                        });
                }


                const minutes = Math.floor(globalTimeRemaining / 60);
                const seconds = globalTimeRemaining % 60;
                globalTimerElement.textContent = `${minutes}:${seconds < 10 ? '0' : ''}${seconds}`;


                if (globalTimeRemaining <= 30) {
                    globalTimerElement.style.color = 'red';
                    globalTimerElement.style.animation = 'pulse 1s infinite';
                }

                globalTimeRemaining--;
            }, 1000);


            validateButton.addEventListener('click', function(event) {
                event.preventDefault();


                if (globalTimeRemaining <= 0) {
                    window.location.href = "{{ path('resultat', {
                        'success': false,
                        'timeout': true,
                        'parties_jouees': parties_jouees|default(0),
                        'score': 0
                    }) }}";
                    return;
                }

                const code = finalCodeInput.value.trim().toUpperCase();

                if (code === '') {
                    alert('Veuillez entrer un code');
                    return;
                }

                fetch('{{ path('validate_answer') }}', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({ code: code, timeRemaining: globalTimeRemaining })
                })
                    .then(response => response.json())
                    .then(data => {
                        if (data.redirectUrl) {
                            window.location.href = data.redirectUrl;
                        } else {
                            alert(data.message || 'Une erreur est survenue.');
                        }
                    })
                    .catch(error => {
                        console.error('Erreur lors de la validation :', error);
                    });
            });


            finalCodeInput.addEventListener('keypress', function(event) {
                if (event.key === 'Enter') {
                    event.preventDefault();
                    validateButton.click();
                }
            });
        });
    </script>
{% endblock %}

templates/jeu/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello JeuController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>/var/www/html/projetSI/src/Controller/JeuController.php</code></li>
        <li>Your template at <code>/var/www/html/projetSI/templates/jeu/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}